theme = "term16_dark"

[editor]
line-number = "relative"
mouse = false
true-color = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
color-modes = true
end-of-line-diagnostics = "hint"
cursorline = true
clipboard-provider = "wayland"
default-yank-register = "+"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = [
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.soft-wrap]
enable = true
max-wrap = 25         # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
# wrap-indicator = ""  # set wrap-indicator to "" to hide it

[keys.normal.space]
# l = ":toggle lsp.display-inlay-hints"
x = { r = ":config-reload", o = ":config-open" }
# b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
b = { c = ":buffer-close" }
g = { b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}" }
l = { g = [
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
], r = { l = ":sh php artisan route:list --except-vendor", t = { b = ":sh php artisan test %{buffer_name}", p = ":sh php artisan test --parallel" }, m = ":sh php artisan migrate" }, m = { f = ":sh php artisan migrate:fresh" } }
# t = { a = ":echo %sh{php artisan test --parallel}}", b = ":echo %sh{php artisan test %{buffer_name}}" }
# m = { m = ":echo %sh{php artisan migrate}", f = ":echo %sh{php artisan migrate:fresh}" }
# C-m = ":sh php artisan migrate:fresh"
# x = ":config-reload"
# C-x = ":config-open"
# C-t = ":echo %sh{php artisan test --parallel}"
# C-b = ":echo %sh{php artisan test %{buffer_name}}"

[keys.normal]
S-h = ":buffer-previous"
S-l = ":buffer-next"
