[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/home/mau/.nix-profile/bin/typescript-language-server"
languages = ["vue"]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "--output.json.path",
  "stdout",
  "--show-stats=false",
  "--issues-exit-code=1",
]

[language-server.laravel-ls]
command = "laravel-ls"

[language-server.phpactor]
command = "phpactor"
args = ["language-server"]

[language-server]
yaml-language-server = { command = "yaml-language-server", args = ["--stdio"] }

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "svelte"
language-servers = ["svelteserver", "tailwindcss-ls"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server"]

[[language]]
name = "php"
auto-format = true
formatter = { command = "pint", args = ["--parallel"] }

[[language]]
name = "blade"
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-ls",
  "laravel-ls",
]

[[language]]
name = "go"
auto-format = true
language-servers = ["gopls", "golangci-lint-lsp"]
